swagger: "2.0"
info: {}
basePath: /v1/api
paths: {}
definitions:
  responses.StandardResponse:
    title: StandardResponse
    type: object
  validation.CreateUserRequest:
    title: CreateUserRequest
    type: object
    properties:
      age:
        type: integer
        format: int64
      email:
        type: string
      name:
        type: string
  validation.UpdateUserRequest:
    title: UpdateUserRequest
    type: object
    properties:
      age:
        type: integer
        format: int64
      name:
        type: string
