swagger: "2.0"
info:
  title: User Management API
  description: API for managing users
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json